-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["bush"] = {
                    
		}
		
		, 
		["hedgehog"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "hedgehog", density = 2, friction = 500, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -147.5, 80  ,  119.5, -122  ,  147.5, -70  ,  -117.5, 125  ,  -147.5, 125  }
                    }
                     ,
                    {
                    pe_fixture_id = "hedgehog", density = 2, friction = 500, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   147.5, -70  ,  119.5, -122  ,  147.5, -108  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "hedgehog", density = 2, friction = 500, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   117.5, 125  ,  -147.5, -74  ,  -114.5, -124  ,  147.5, 80  ,  147.5, 125  }
                    }
                     ,
                    {
                    pe_fixture_id = "hedgehog", density = 2, friction = 500, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -114.5, -124  ,  -147.5, -74  ,  -147.5, -109  }
                    }
                    
                    
                    
		}
		
		, 
		["polygon-beach"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "terrain-beach", density = 2, friction = 50, bounce = 0.5, 
                    filter = { categoryBits = 32768, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1614.5, -124  ,  -2500.5, 181  ,  -2501.5, -181  }
                    }
                     ,
                    {
                    pe_fixture_id = "terrain-beach", density = 2, friction = 50, bounce = 0.5, 
                    filter = { categoryBits = 32768, maskBits = 65535, groupIndex = 0 },
                    shape = {   -236.5, -54  ,  2499.5, 181  ,  -2500.5, 181  ,  -1614.5, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "terrain-beach", density = 2, friction = 50, bounce = 0.5, 
                    filter = { categoryBits = 32768, maskBits = 65535, groupIndex = 0 },
                    shape = {   2499.5, 181  ,  -236.5, -54  ,  2499.5, 61  }
                    }
                    
                    
                    
		}
		
		, 
		["cliff"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "cliff", density = 2, friction = 50, bounce = 0.2, 
                    filter = { categoryBits = 32768, maskBits = 65535, groupIndex = 0 },
                    shape = {   180, -243.5  ,  198, -177.5  ,  188, -168.5  ,  -332, -4.5  ,  -333, -238.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "cliff", density = 2, friction = 50, bounce = 0.2, 
                    filter = { categoryBits = 32768, maskBits = 65535, groupIndex = 0 },
                    shape = {   266, -87.5  ,  293, -22.5  ,  296, 39.5  ,  -332, -4.5  ,  204, -135.5  ,  232, -130.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "cliff", density = 2, friction = 50, bounce = 0.2, 
                    filter = { categoryBits = 32768, maskBits = 65535, groupIndex = 0 },
                    shape = {   198, -177.5  ,  180, -243.5  ,  195, -227.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "cliff", density = 2, friction = 50, bounce = 0.2, 
                    filter = { categoryBits = 32768, maskBits = 65535, groupIndex = 0 },
                    shape = {   -332, -4.5  ,  188, -168.5  ,  204, -135.5  }
                    }
                    
                    
                    
		}
		
		, 
		["sandbag1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20, -43.5  ,  20, -43.5  ,  50, -9.5  ,  46, 31.5  ,  -30, 43.5  ,  -50, 25.5  ,  -50, -12.5  ,  -41, -34.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   50, -9.5  ,  20, -43.5  ,  38, -36.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, 25.5  ,  -30, 43.5  ,  -42, 38.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30, 43.5  ,  46, 31.5  ,  33, 43.5  }
                    }
                    
                    
                    
		}
		
		, 
		["sandbag2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 43  ,  -32.5, 44  ,  -48.5, -6  ,  -41.5, -36  ,  16.5, -43  ,  45.5, -11  ,  48.5, 17  ,  47.5, 37  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48.5, 31  ,  -48.5, -6  ,  -32.5, 44  ,  -41.5, 41  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   45.5, -11  ,  16.5, -43  ,  34.5, -32  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -41.5, -36  ,  -28.5, -44  ,  16.5, -43  }
                    }
                    
                    
                    
		}
		
		, 
		["sandbag3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, -24.5  ,  49, -0.5  ,  -26, 41.5  ,  -50, -11.5  ,  -44, -32.5  ,  -33, -41.5  ,  22, -40.5  ,  36, -36.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   36, 41.5  ,  -26, 41.5  ,  49, -0.5  ,  50, 33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "sandbag", density = 2, friction = 250, bounce = 0.1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 27.5  ,  -50, -11.5  ,  -26, 41.5  ,  -47, 36.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

