-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["wheel_back"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "wheel", density = 8, friction = 100, bounce = 0.1, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    radius = 31.064
                    }
                    
                    
		}
		
		, 
		["wheel_front"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "wheel", density = 8, friction = 100, bounce = 0.1, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    radius = 24.469
                    }
                    
                    
		}
		
		, 
		["barell"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "barell", density = 2, friction = 10, bounce = 0.30000000000000004, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    shape = {   -91, -3.5  ,  25, -2.5  ,  22, 11.5  ,  -92, 12.5  ,  -98.5, 7  ,  -98.5, 1  }
                    }
                     ,
                    {
                    pe_fixture_id = "barell", density = 2, friction = 10, bounce = 0.30000000000000004, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    shape = {   85, 22.5  ,  69, 22.5  ,  35, -5.5  ,  47, -23.5  ,  85, -22.5  ,  97.5, -9  ,  97.5, 7  ,  93, 18.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "barell", density = 2, friction = 10, bounce = 0.30000000000000004, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    shape = {   97.5, -9  ,  85, -22.5  ,  93, -18.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "barell", density = 2, friction = 10, bounce = 0.30000000000000004, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    shape = {   47, -23.5  ,  35, -5.5  ,  41.5, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "barell", density = 2, friction = 10, bounce = 0.30000000000000004, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    shape = {   22, 11.5  ,  25, -2.5  ,  35, -5.5  ,  62, 17.5  ,  28, 17.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "barell", density = 2, friction = 10, bounce = 0.30000000000000004, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    shape = {   35, -5.5  ,  69, 22.5  ,  62, 17.5  }
                    }
                    
                    
                    
		}
		
		, 
		["body"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "0300-armor-0900", density = 2, friction = 0, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -170, -71  ,  201, -70  ,  201, 67  ,  -170, 76  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "0300-engine-0900", density = 2, friction = 0, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   319, 18  ,  269, 68  ,  200, 68  ,  200, -69  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "0500-armor-1500", density = 2, friction = 0, bounce = 0.7, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -171, 26  ,  -308, 24  ,  -171, -69  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "0400-tracks-1200", density = 2, friction = 0, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -266, 63  ,  -307, 25  ,  -169, 25  ,  -170, 74  }
                    }
                    
                    
                    
		}
		
		, 
		["tower"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "0400-armor-1200", density = 2, friction = 0, bounce = 0.4, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4.5, -31.5  ,  87.5, -28.5  ,  120.5, 26.5  ,  -79.5, 31.5  ,  -80.5, -27.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "0400-barell-1200", density = 2, friction = 0, bounce = 0.6, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -109.5, -18.5  ,  -80.5, -27.5  ,  -80.5, 31.5  ,  -108.5, 21.5  ,  -121.5, 0.5  }
                    }
                    
                    
                    
		}
		
		, 
		["wheel"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "wheel", density = 8, friction = 100, bounce = 0.1, 
                    filter = { categoryBits = 8192, maskBits = 65535, groupIndex = 0 },
                    radius = 45.233
                    }
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

